language: rust

rust: nightly

cache: cargo

script:
  - cargo build --verbose 
  - cargo test --verbose

before_install:
  - sudo apt-get -qq install -y libcurl4-openssl-dev libelf-dev libdw-dev
  - sudo apt-get -qq install 
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo apt-get -qq update
  - sudo apt-get install -qq intel-mkl-64bit-2018.2-046

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/mole-*
