language: rust

rust: nightly

cache: cargo

script:
  - cargo test --verbose

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y libcurl4-openssl-dev libelf-dev libdw-dev
  - sudo apt-get -qq install gfortran
  - sudo apt-get -qq install liblapack-dev liblapack3 libopenblas-base libopenblas-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. && rm -rf target/debug/mole* && cargo test --no-run &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/mole-*
