[package]
name = "mole"
version = "0.1.0"
authors = ["Jesse van Rhijn <jesse.v.rhijn@gmail.com>"]

[dependencies]
rand = "0.5.5"
ndarray = { version = "0.12.0", features = ["blas"] }
blas-src = { version = "0.2.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6.0", default-features = false, features = ["cblas", "system"] }
ndarray-rand = "0.8.0"
ndarray-linalg = "0.10.0"
assert = "0.7.4"
