[package]
name = "mole"
version = "0.2.0"
authors = ["Jesse van Rhijn <jesse.v.rhijn@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "lib/basis",
  "lib/metropolis",
  "lib/montecarlo",
  "lib/operator",
  "lib/optimizers",
  "lib/wavefunction",
]

[dependencies]
montecarlo = { path = "lib/montecarlo" }
wavefunction = { path = "lib/wavefunction" }
metropolis = { path = "lib/metropolis" }
operator = { path = "lib/operator" }
basis = { path = "lib/basis" }
rand = "0.5.0"
ndarray = "0.12.0"
ndarray-linalg = { version = "0.10.0", features = ["intel-mkl"] }
ndarray-rand = "0.8.0"
num-traits = "0.2"
itertools = "0.7"
