[package]
name = "mole"
version = "0.1.0"
authors = ["Jesse van Rhijn <jesse.v.rhijn@gmail.com>"]

[dependencies]
rand = "0.5.0"
ndarray = "0.12.0"
ndarray-linalg = "0.10.0"
openblas-src = "0.5"
ndarray-rand = "0.8.0"

