[package]
name = "metropolis"
version = "0.1.0"
authors = ["Jesse van Rhijn <jesse.v.rhijn@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.5.0"
ndarray = "0.12.0"
ndarray-linalg = "0.10.0"
ndarray-rand = "0.8.0"
wavefunction_traits = { path = "../wavefunction_traits" }

